--5. MAGNITUDE ANALYSIS

--Find total customers by countries
SELECT COUNT(customer_number) as customer_number,country
FROM Gold.dim_customers
GROUP BY country
ORDER BY customer_number DESC

--Find total customers by gender
SELECT COUNT(customer_number) as customer_number,gender
FROM Gold.dim_customers
GROUP BY gender
ORDER BY customer_number DESC

--Find total products by category
SELECT COUNT(product_number) as product_number,category
FROM Gold.dim_products
GROUP BY category
ORDER BY product_number DESC

--What is the average costs in each category?
SELECT AVG(cost) as avg_cost,category
FROM Gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

--What is the total revenue generated for each category?
SELECT 
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


--Find total revenue is generated by each customer
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

--What is the distribution of sold items across countries?
SELECT 
    c.country,
    SUM(f.quantity) AS total_items_sold
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_items_sold DESC;